export const UI = {
  en: {
    show_numbers: 'Show numbers',
    hide_numbers: 'Hide numbers',
    days_repair: 'Days / repair by year',
    wip_jobs: 'WIP jobs by year',
    template_status: 'Template On vs Off vs 2024 target',
    equipment_mix: 'Equipment mix',
    by_quarter: '2025 days / repair by quarter',
    by_branch: '2025 avg days by branch',
    by_department: '2025 avg days by department',
    slips: 'Biggest slips 2025 vs 2024',
    improves: 'Biggest improves 2025 vs 2024',
    quality_line: '2024 quality baseline',
    closed: 'Closed',
    avg_days: 'Avg days',
    wip: 'WIP (jobs)',
    repeat: 'Repeat repair',
    assets: 'Unique assets',
    year_default: '2026',
    off_templates: 'Off-target templates',
    none_off: 'No off-target templates',
    loading: 'Loading dashboard…',
    load_error: 'Could not load KPI data.',
    q: 'Q',
    d24: '2024 days',
    d25: '2025 days',
    share: 'Share',
    closed_col: 'Closed',
    avg_col: 'Avg days',
    target_col: 'Target',
    status_col: 'Status',
    template: 'Template',
    year: 'Year',
    equipment: 'Equipment',
    branch: 'Branch',
    department: 'Department',
    quarter: 'Quarter',
    confidential: 'Confidential',
    source: 'Source',
    as_of: 'As of',
    wip_ytd: '2026 YTD',
    wip_ann: '2026 annualized',
    wip_div_ytd: '÷245 calendar days',
    wip_div_ann: '÷365 calendar days',
    wip_div_2024: '÷366 leap year',
    wip_div_2025: '÷365 calendar days',
    job_weighted: 'Official company days/repair is the job-weighted closed average.',
    unweighted: 'Unweighted template averages — not the company number.',
    absent: 'Absent in extract',
    no_baseline: 'No 2024 baseline',
    company_status: 'Company quality vs 2024',
    sec_defs: 'Definitions',
    sec_company: 'Company quality & load',
    sec_breaks: 'Where performance breaks',
    sec_limits: 'Data limits',
    sec_reco: 'Recommended actions',
    def_closed: 'Closed = column G filled.',
    def_cycle: 'Cycle time = calendar Closed − Created (not workdays).',
    def_year: 'Year = Created year, not Closed year.',
    def_units: 'Quality is days/repair. Capacity is WIP jobs. Never the same axis.',
    limit_helix: 'Helix and IMPACCT are absent in this extract — shown as 0 / no 2024 baseline, not invented.',
    limit_r: 'Days/repair (column R) are pasted values, not live formulas.',
    limit_opens: 'All open work orders are in 2026.',
    limit_year: 'Created year ≠ Closed year on 550 of 2,711 closed jobs. KPIs use Created year.',
    reco_1: 'Hold the 2024 quality baseline (~27.32 days). Do not reset it to 2025 or 2026.',
    reco_2: 'Treat 2026 as In Progress while opens remain.',
    reco_3: 'Attack high-n slips and the 2024 → 2025 WIP jump (45.5 → 89.2 jobs).',
  },
  es: {
    show_numbers: 'Ver números',
    hide_numbers: 'Ocultar números',
    days_repair: 'Días / reparación por año',
    wip_jobs: 'Trabajos WIP por año',
    template_status: 'Plantillas Dentro vs Fuera vs objetivo 2024',
    equipment_mix: 'Mezcla de equipo',
    by_quarter: '2025 días / reparación por trimestre',
    by_branch: '2025 días promedio por sucursal',
    by_department: '2025 días promedio por departamento',
    slips: 'Mayores deslizamientos 2025 vs 2024',
    improves: 'Mayores mejoras 2025 vs 2024',
    quality_line: 'Línea base de calidad 2024',
    closed: 'Cerradas',
    avg_days: 'Días prom.',
    wip: 'WIP (trabajos)',
    repeat: 'Reparación repetida',
    assets: 'Activos únicos',
    year_default: '2026',
    off_templates: 'Plantillas fuera de objetivo',
    none_off: 'Sin plantillas fuera de objetivo',
    loading: 'Cargando tablero…',
    load_error: 'No se pudo cargar los datos KPI.',
    q: 'T',
    d24: 'Días 2024',
    d25: 'Días 2025',
    share: 'Participación',
    closed_col: 'Cerradas',
    avg_col: 'Días prom.',
    target_col: 'Objetivo',
    status_col: 'Estado',
    template: 'Plantilla',
    year: 'Año',
    equipment: 'Equipo',
    branch: 'Sucursal',
    department: 'Departamento',
    quarter: 'Trimestre',
    confidential: 'Confidencial',
    source: 'Fuente',
    as_of: 'Al',
    wip_ytd: '2026 YTD',
    wip_ann: '2026 anualizado',
    wip_div_ytd: '÷245 días de calendario',
    wip_div_ann: '÷365 días de calendario',
    wip_div_2024: '÷366 año bisiesto',
    wip_div_2025: '÷365 días de calendario',
    job_weighted: 'Los días/reparación oficiales de la empresa son el promedio ponderado por trabajos cerrados.',
    unweighted: 'Promedios de plantilla sin ponderar — no es el número de la empresa.',
    absent: 'Ausente en el extracto',
    no_baseline: 'Sin línea base 2024',
    company_status: 'Calidad de empresa vs 2024',
    sec_defs: 'Definiciones',
    sec_company: 'Calidad y carga de la empresa',
    sec_breaks: 'Dónde se rompe el desempeño',
    sec_limits: 'Límites de los datos',
    sec_reco: 'Acciones recomendadas',
    def_closed: 'Cerrada = columna G llena.',
    def_cycle: 'Tiempo de ciclo = calendario Cerrada − Creada (no días hábiles).',
    def_year: 'Año = año de Creación, no de Cierre.',
    def_units: 'Calidad es días/reparación. Capacidad es trabajos WIP. Nunca el mismo eje.',
    limit_helix: 'Helix e IMPACCT no están en este extracto — se muestran como 0 / sin línea base 2024, no se inventan.',
    limit_r: 'Días/reparación (columna R) son valores pegados, no fórmulas vivas.',
    limit_opens: 'Todas las órdenes abiertas están en 2026.',
    limit_year: 'Año de creación ≠ año de cierre en 550 de 2,711 trabajos cerrados. Los KPI usan el año de creación.',
    reco_1: 'Mantener la línea base de calidad 2024 (~27.32 días). No resetearla a 2025 o 2026.',
    reco_2: 'Tratar 2026 como En progreso mientras haya abiertas.',
    reco_3: 'Atacar los deslizamientos de alto n y el salto de WIP 2024 → 2025 (45.5 → 89.2 trabajos).',
  },
}
